using Npgsql;
using NpgsqlTypes;

namespace Legacy.Maliev.AppHost.MigrationRunner;

public static class CatalogSnapshotComposer
{
    public static async Task ComposeCurrenciesAsync(
        string currencyConnectionString,
        string catalogConnectionString,
        CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(currencyConnectionString);
        ArgumentException.ThrowIfNullOrWhiteSpace(catalogConnectionString);

        var currencies = new List<CurrencyRow>();
        await using (var source = new NpgsqlConnection(currencyConnectionString))
        {
            await source.OpenAsync(cancellationToken);
            await using var command = new NpgsqlCommand(
                "SELECT \"ID\", \"ShortName\", \"LongName\", \"CreatedDate\", \"ModifiedDate\" FROM \"Currency\" ORDER BY \"ID\"",
                source);
            await using var reader = await command.ExecuteReaderAsync(cancellationToken);
            while (await reader.ReadAsync(cancellationToken))
            {
                currencies.Add(new(
                    reader.GetInt32(0),
                    reader.GetString(1),
                    reader.GetString(2),
                    reader.IsDBNull(3) ? null : reader.GetDateTime(3),
                    reader.IsDBNull(4) ? null : reader.GetDateTime(4)));
            }
        }

        await using var target = new NpgsqlConnection(catalogConnectionString);
        await target.OpenAsync(cancellationToken);
        await using var transaction = await target.BeginTransactionAsync(cancellationToken);
        await using (var prepare = new NpgsqlCommand("""
            CREATE TABLE IF NOT EXISTS "Currency" (
                "ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "ShortName" character varying(10) NOT NULL,
                "LongName" character varying(50) NOT NULL,
                "CreatedDate" timestamp without time zone NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
                "ModifiedDate" timestamp without time zone NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'));
            TRUNCATE TABLE "Currency" RESTART IDENTITY;
            """, target, transaction))
        {
            await prepare.ExecuteNonQueryAsync(cancellationToken);
        }

        await using (var insert = new NpgsqlCommand("""
            INSERT INTO "Currency" ("ID", "ShortName", "LongName", "CreatedDate", "ModifiedDate")
            VALUES ($1, $2, $3, $4, $5)
            """, target, transaction))
        {
            insert.Parameters.Add(new NpgsqlParameter<int> { NpgsqlDbType = NpgsqlDbType.Integer });
            insert.Parameters.Add(new NpgsqlParameter<string> { NpgsqlDbType = NpgsqlDbType.Varchar });
            insert.Parameters.Add(new NpgsqlParameter<string> { NpgsqlDbType = NpgsqlDbType.Varchar });
            insert.Parameters.Add(new NpgsqlParameter<DateTime?> { NpgsqlDbType = NpgsqlDbType.Timestamp });
            insert.Parameters.Add(new NpgsqlParameter<DateTime?> { NpgsqlDbType = NpgsqlDbType.Timestamp });
            await insert.PrepareAsync(cancellationToken);

            foreach (var currency in currencies)
            {
                insert.Parameters[0].Value = currency.Id;
                insert.Parameters[1].Value = currency.ShortName;
                insert.Parameters[2].Value = currency.LongName;
                insert.Parameters[3].Value = currency.CreatedDate;
                insert.Parameters[4].Value = currency.ModifiedDate;
                await insert.ExecuteNonQueryAsync(cancellationToken);
            }
        }

        await using (var sequence = new NpgsqlCommand("""
            SELECT setval(
                pg_get_serial_sequence('"Currency"', 'ID'),
                COALESCE(MAX("ID"), 1),
                EXISTS (SELECT 1 FROM "Currency"))
            FROM "Currency";
            """, target, transaction))
        {
            await sequence.ExecuteNonQueryAsync(cancellationToken);
        }

        await transaction.CommitAsync(cancellationToken);
    }

    private sealed record CurrencyRow(
        int Id,
        string ShortName,
        string LongName,
        DateTime? CreatedDate,
        DateTime? ModifiedDate);
}
