name: Develop validation

on:
  push:
    branches: [develop]

permissions:
  contents: read

concurrency:
  group: apphost-develop-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    uses: ./.github/workflows/_build-and-test.yml
