name: Staging validation

on:
  push:
    tags: [release/v*]
permissions:
  contents: read

concurrency:
  group: apphost-staging-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    uses: ./.github/workflows/_build-and-test.yml
